# Generated by Django 4.0.6 on 2022-07-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qantyty',
            new_name='quantity',
        ),
    ]
