# Generated by Django 4.1 on 2022-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_pieces',
            field=models.IntegerField(null=True),
        ),
    ]
