# Generated by Django 4.1 on 2022-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_nauser_order_nacustomer_shippingadress_nacustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauser',
            name='shortHash',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nauser',
            name='shortHashName',
            field=models.BigIntegerField(null=True),
        ),
    ]
