# Generated by Django 4.1 on 2022-10-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_nauser_shorthash_nauser_shorthashname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nauser',
            old_name='name',
            new_name='csrfName',
        ),
    ]
