# Generated by Django 4.1 on 2022-10-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_name_nauser_csrfname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nauser',
            name='shortHash',
        ),
        migrations.RemoveField(
            model_name='nauser',
            name='shortHashName',
        ),
    ]
