# Generated by Django 4.1 on 2022-10-21 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_nauser_shorthash_remove_nauser_shorthashname'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 21, 11, 52, 23, 44357, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nauser',
            name='shortName',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
