# Generated by Django 4.1 on 2022-10-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_nauser_date_created_nauser_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nauser',
            name='shortName',
        ),
    ]
