# Generated by Django 4.1 on 2022-10-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_nauser_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauser',
            name='shortName',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
